---
title: "`synimu` Vignettes"
bibliography: biblio.bib
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Simulations from Time Series Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In @zhang2021scalewise, we introduce a method allowing to compute synthetic (or average) signals issued from multiple correlated and/or even non-stationary signals. In a nutshell, this method minimizes a weighted average of the wavelet variance of the synthetic signal whose weights can be chosen depending on the application at hand. This method is illustrated with gyroscopes which often contain non-stationary processes such as random walks. This package implements the method of @zhang2021scalewise, called Scale-wise Variance Optimization or SVO, as well as the approach of @s17020352, which is used as a comparison.

# Data generation

The package `synimu` allows to simulate data from various multivariate composite (or latent) time series models. For example, consider the model "white noise +  random walk", which in a multivariate setting can be expressed as follows. Let $W_t \sim \mathcal{N}(\mathbf{0}, \mathbf{R})$, $Y_t \sim \mathcal{N}(\mathbf{0}, \mathbf{Q})$ and

$$X_t = X_{t-1} + Y_t,$$
where $\mathbf{R}$ and $\mathbf{Q}$ are covariance matrices. Then, we assume that $X_t$, $W_t$ and $Y_t$ are latent but we observe $Z_t$ which is defined as

$$Z_t = X_t + W_t.$$


state-space models


Generate sample data from a gyroscope array following a white noise plus random walk error model

```{r}
library(synimu)
```
kjg

@cobb1978problem

# ref
